#发送方服务器配置
mail:
  smtp:
    #发送方服务器地址
    host: smtp.qq.com
    port: 587
    #发送方邮箱地址
    fromAddress: 1035518425@qq.com
    #发送方邮箱密码（授权码）
    password: arcgssraefgrbcdi
    #编码格式
    default-encoding: utf-8
    transport:
      protocol: smtp
    auth: true
    starttls:
      enable: true
    socketFactory:
      port: 587
      class: javax.net.ssl.SSLSocketFactory
      fallback: false

test: test


